dist: trusty
sudo: required
language: python
python:
  - "3.5"
before_install:
  - sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable -y
  - sudo add-apt-repository ppa:juju/stable -y
  - sudo apt-get update -q
  - sudo apt-get install lxd juju -y
  - newgrp lxd
  - sudo lxd init --auto
install: pip install tox-travis
before_script:
  - juju bootstrap localhost test
script: tox
after_script:
  - juju destroy-controller --destroy-all-models -y test
